feat(modules): add container-instance module
CHUPITO-Org/IaC-Chupito-Azure pull request #11
Opened 2023-11-15 20:16 UTC by pamelaluquemck

## Conference App - Azure Cloud

## Issue ticket number and link
https://trello.com/c/YL8m23Kc

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] My changes generate no new warnings or errors

## Pull request type

Please check the type of change your PR introduces:

- [x] :sparkles: Feature Implementation
- [ ] :bug: Bugfix
- [ ] :art: Code Formatting (formatting, renaming)
- [ ] :recycle: Refactoring
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :hammer: Automated testing
- [ ] :zap:  Dependency update
- [ ] :wrench: Add or update configuration files

## What is the current module?

-

## What is the new behavior?

- Add container instance module

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-11-16 05:35 UTC, jose-sal-y-rosas requested changes
Please review feefback

2023-11-16 05:35 UTC, jose-sal-y-rosas commented on modules/container-instance/main.tf
> +
Please remove one empty line here

2023-11-16 05:35 UTC, jose-sal-y-rosas commented on modules/container-instance/main.tf
> +  os_type             = var.os_type
Is this required as a variable? Do you think we are going to change it?

2023-11-16 05:35 UTC, jose-sal-y-rosas commented on modules/container-registry/main.tf
> +  value = azurerm_container_registry.acr.login_server
Please add an empty line

2023-11-16 12:53 UTC, pramirezma reviewed
Please use a linter that can "fix on save" so you won't have those readability problems

2023-11-16 15:46 UTC, pamelaluquemck commented on modules/container-instance/main.tf
> +  os_type             = var.os_type
As we can reutilize the module if the architecture gets more complex I think it could change but in the variables.tf (root) I can define a default value for the location, resource group and os_type. The ip_address_type could take the value of private or public and I really think it could change

2023-11-16 22:43 UTC, pramirezma approved these changes

2023-11-16 23:35 UTC, jose-sal-y-rosas requested changes
Please review comment

2023-11-16 23:35 UTC, jose-sal-y-rosas commented on modules/container-instance/main.tf
> +  os_type             = var.os_type
When it is going to be complex? Most of the time, we assume this, but in real projects there is no chance to change, at least not in short terms.

2023-11-20 20:19 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-11-20 20:20 UTC, merged