feat(docs): Update README.md and modify pre-commit hook
CHUPITO-Org/IaC-Chupito-Azure pull request #20
Opened 2023-12-11 17:03 UTC by pamelaluquemck

## Conference App - Azure Cloud

## Issue ticket number and link
https://trello.com/c/Tgj95B6d/296-azure-actualizar-el-readme

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] My changes generate no new warnings or errors

## Pull request type

Please check the type of change your PR introduces:

- [ ] :sparkles: Feature Implementation
- [ ] :bug: Bugfix
- [ ] :art: Code Formatting (formatting, renaming)
- [ ] :recycle: Refactoring
-  [x] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :hammer: Automated testing
- [ ] :zap:  Dependency update
- [ ] :wrench: Add or update configuration files

## What is the current module?

- Pre-commit hook modify README.md 

## What is the new behavior?

- Pre-commit hook modify ./docs/README-tech.md and there is an update of README.md

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-12-11 17:13 UTC, pramirezma requested changes
This doesn't follows terraform documentation practices, also, the readme steps are unnecessary when you have a pipeline installed. And there are heavily opinionated of your installation, the use of terraform and all services SHOULD be portable.
please don't upload init files with credentials.

2023-12-11 17:28 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-12-11 17:28 UTC, jose-sal-y-rosas commented on README.md
> +## Test the deployment
Please move all this section to another README file.

2023-12-11 17:28 UTC, jose-sal-y-rosas commented on README.md
> +      docker tag [frontend-image] azcapabilitiesacr.azurecr.io/ms-conference-ui
use the same format of the image to identify container registry. Avoid using real names.

2023-12-11 17:28 UTC, jose-sal-y-rosas commented on README.md
> +      docker buildx build --platform linux/amd64 -t image-mongo:v1 . -f Dockerfile
What is the purpose of buildx here?

2023-12-11 17:28 UTC, jose-sal-y-rosas commented on dev.auto.example.tfvars
> +client_id        = "Change this value"
Rename this file according to the comment in the README file.

2023-12-11 18:23 UTC, pamelaluquemck commented on README.md
> +      docker tag [frontend-image] azcapabilitiesacr.azurecr.io/ms-conference-ui
Ok

2023-12-12 15:59 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-12-12 16:07 UTC, pramirezma requested changes

2023-12-12 16:07 UTC, pramirezma commented on docs/ADR.md
>  Costo por mes durante 24 horas:
id this supposed to be in Spanish?

2023-12-12 16:07 UTC, pramirezma commented on testing.md
> +Navigate in your browser:http://az-capabilities-dns.eastus2.cloudapp.azure.com/
this should depend of the cloud app name, if you change the variable you change this hostname

2023-12-12 16:07 UTC, pramirezma commented on README.md
> +
do we need "local deployment"

2023-12-12 16:15 UTC, pamelaluquemck commented on docs/ADR.md
>  Costo por mes durante 24 horas:
No, I'll translate to english

2023-12-12 16:15 UTC, pamelaluquemck commented on testing.md
> +Navigate in your browser:http://az-capabilities-dns.eastus2.cloudapp.azure.com/
I'll put a general name instead

2023-12-12 16:17 UTC, pamelaluquemck commented on README.md
> +
Could be an option. But as we are using terraform cloud now I will remove from the readme

2023-12-12 16:33 UTC, pramirezma commented on docs/ADR.md
>  Costo por mes durante 24 horas:
Still saying "Costo por mes durante 24 horas:"

2023-12-12 16:35 UTC, pramirezma commented on docs/ADR.md
>  Costo por mes durante 24 horas:
now is displaying correctly

2023-12-12 16:55 UTC, merged