feat: Adding rg, vnet, container registry
CHUPITO-Org/IaC-Chupito-Azure pull request #6
Opened 2023-11-10 12:29 UTC by pamelaluquemck

2023-11-10 19:43 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-10 19:43 UTC, jose-sal-y-rosas commented on main.tf
> +resource "azurerm_resource_group" "az-capabilities-rg" {
Why do we need to create a resource group? Please us the specific resource group for the project.

2023-11-10 19:49 UTC, pamelaluquemck commented on main.tf
> +resource "azurerm_resource_group" "az-capabilities-rg" {
There is no resource group in the subscription 
![image](https://github.com/CHUPITO-Org/IaC-Chupito-Azure/assets/130703559/d56e11f3-59e4-4147-abf1-3587b8a3246a)

2023-11-10 20:10 UTC, pramirezma requested changes

2023-11-10 20:10 UTC, pramirezma commented on main.tf
> +  sku                 = "Standard"
Seems that there is no closing bracket for this resource

2023-11-10 20:11 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-11-13 20:15 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-13 20:15 UTC, jose-sal-y-rosas commented on main.tf
> +module "az-capabilities-vnet-1" {
I think this module could be titled more general, something like: module "network"

2023-11-13 22:18 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-13 22:18 UTC, jose-sal-y-rosas commented on .trunk/trunk.yaml
> -    - terrascan@1.18.3
why do we need to remove this libraries? Are they not required?

2023-11-13 22:31 UTC, pamelaluquemck commented on .trunk/trunk.yaml
> -    - terrascan@1.18.3
We are using tfsec so terrascan it's not required as these do the same function

2023-11-13 22:59 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-11-14 14:40 UTC, pramirezma approved these changes

2023-11-14 15:00 UTC, merged